#@author dushmanthab99@gmail.com
#Horozontal pod scalar
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: jvb-pod-scaler
  namespace : jitsi
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: jvb
  targetCPUUtilizationPercentage: 80
