#!/usr/bin/with-contenv bash

#export LOCAL_ADDRESS=$(ip addr show dev "$(ip route|awk '/^default/ { print $5 }')" | grep -oP '(?<=inet\s)\d+(\.\d+){3}')

if [[ -z $JVB_AUTH_PASSWORD ]]; then
    echo 'FATAL ERROR: JVB auth password must be set'
    exit 1
fi

OLD_JVB_AUTH_PASSWORD=passw0rd
if [[ "$JVB_AUTH_PASSWORD" == "$OLD_JVB_AUTH_PASSWORD" ]]; then
    echo 'FATAL ERROR: JVB auth password must be changed, check the README'
    exit 1
fi


echo "SETTING JVB_PORT..."

echo "HOST NAME:" "$HOSTNAME"
IFS='-' read -ra ADDR <<< "$HOSTNAME"
let jvb_port=$((31000+${ADDR[1]}))
export JVB_PORT="$jvb_port"
echo $JVB_PORT
echo "========JVB_PORT:""$JVB_PORT""=================="

docker_host_addr_varname=DOCKER_HOST_ADDR${ADDR[1]}
export DOCKER_HOST_ADDRESS="${!docker_host_addr_varname}"
echo $DOCKER_HOST_ADDRESS
echo "========DOCKER_HOST_ADDRESS:""$DOCKER_HOST_ADDRESS""=================="

tpl /defaults/sip-communicator.properties > /config/sip-communicator.properties
echo "Adding org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=""$DOCKER_LOCAL_ADDR"" to /config/sip-communicator.properties"
echo "org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=""$DOCKER_LOCAL_ADDR" >> /config/sip-communicator.properties
echo "Adding org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=""$DOCKER_HOST_ADDRESS"" to /config/sip-communicator.properties"
echo "org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=""$DOCKER_HOST_ADDRESS" >> /config/sip-communicator.properties
if [[ -f /config/custom-sip-communicator.properties ]]; then
    cat /config/custom-sip-communicator.properties >> /config/sip-communicator.properties
fi

tpl /defaults/jvb.conf > /config/jvb.conf

if [[ ! -f /config/logging.properties ]]; then
    cp /defaults/logging.properties /config
fi

chown -R jvb:jitsi /config
