apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging2
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: petrag@andrew.cmu.edu # CHANGE THIS TO YOUR OWN EMAIL ADDRESS
    privateKeySecretRef:
      name: letsencrypt-staging2
    solvers:
      - http01:
          ingress: {}
