{
 "title": "Jitsi Cluster",
 "description": "Performance metrics of Vmeeting cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "jitsi_host",
    "label": "Vmeeting Servers",
    "query": "select DISTINCT(\"host\") from (select \"host\",last(\"conferences\") from \"jitsi_stats\" where $timeFilter group by \"host\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Conferences running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT sum(\"x\") FROM (SELECT last(\"conferences\") AS \"x\" FROM \"jitsi_stats\" WHERE (\"host\" =~ /./) AND $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "conferences" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Largest Conference",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "jitsi_stats",
     "query": "SELECT last(\"largest_conference\") FROM \"jitsi_stats\" WHERE (\"host\" =~ /./) AND $timeFilter",
     "select": [
      [
       { "params": [ "largest_conference" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Total Participants",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "jitsi_stats",
     "query": "SELECT sum(\"x\") from (SELECT last(\"participants\") AS \"x\" FROM \"jitsi_stats\" WHERE (\"host\" =~ /./) AND $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "participants" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Video Channels",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT sum(\"x\") FROM (SELECT last(\"endpoints_sending_video\") AS \"x\" FROM \"jitsi_stats\" WHERE $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "videochannels" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audio channels",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT sum(\"x\") FROM (SELECT last(\"endpoints_sending_audio\") AS \"x\" FROM \"jitsi_stats\" WHERE $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "endpoints_sending_audio" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recordings",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "jicofo_stats",
     "select": [
      [
       { "params": [ "recording_active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Live streams",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "jicofo_stats",
     "select": [
      [
       { "params": [ "live_streaming_active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Jibri remain",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "jicofo_stats",
     "select": [
      [
       { "params": [ "jibri_detector_available" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/./" }
     ]
    }
   ]
  },
  { "title": "Jitsi Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"jitsi\", pod=~\"jitsi-.*\", container=~\".*\", container!=\"POD\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"jitsi\", image!=\"\", pod=~\"jitsi-.*\", container=~\".*\", container!=\"POD\"}[4m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"jitsi\", pod=~\"jitsi-.*\"}[4m])))",
     "legendFormat": "RX"
    },
    {
     "expr": "sort_desc(sum by (pod) (irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"jitsi\", pod=~\"jitsi-.*\"}[4m])))",
     "legendFormat": "TX"
    }
   ]
  },
  { "title": "Jitsi Videobridge $jitsi_host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "jitsi_host" },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"jitsi\", pod=\"$jitsi_host\", container=\"jvb\"})",
     "legendFormat": "jvb"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"jitsi\", image!=\"\", pod=\"$jitsi_host\", container=\"jvb\"}[4m]))",
     "legendFormat": "jvb"
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "server_incoming",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "bit_rate_download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    },
    {
     "alias": "server_outgoing",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "bit_rate_upload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Loss Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "server_incoming",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "loss_rate_download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    },
    {
     "alias": "server_outgoing",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "loss_rate_upload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "participants",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT \"participants\" FROM \"jitsi_stats\" WHERE (\"host\" =~ /^$jitsi_host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "participants" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    }
   ]
  },
  { "title": "Jitsi Videobridge $jitsi_host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"jitsi\", pod=\"$jitsi_host\", container=\"jvb\"})",
     "legendFormat": "jvb"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"jitsi\", image!=\"\", pod=\"$jitsi_host\", container=\"jvb\"}[4m]))",
     "legendFormat": "jvb"
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "alias": "server_incoming",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "bit_rate_download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    },
    {
     "alias": "server_outgoing",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "bit_rate_upload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Loss Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "server_incoming",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "loss_rate_download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    },
    {
     "alias": "server_outgoing",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "select": [
      [
       { "params": [ "loss_rate_upload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "participants",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT \"participants\" FROM \"jitsi_stats\" WHERE (\"host\" =~ /^$jitsi_host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "participants" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$jitsi_host$/" }
     ]
    }
   ]
  }
 ]
}