apiVersion: v1
kind: ConfigMap
metadata:
  name: jibri-env
  #namespace: jibri
  namespace: jitsi
data:
  #XMPP_AUTH_DOMAIN: auth.meet.jitsi
  XMPP_AUTH_DOMAIN: auth.jitsicluster.eastus.cloudapp.azure.com
  #XMPP_INTERNAL_MUC_DOMAIN: internal-muc.meet.jitsi
  XMPP_INTERNAL_MUC_DOMAIN: internal-muc.jitsicluster.eastus.cloudapp.azure.com
  #XMPP_RECORDER_DOMAIN: recorder.meet.jitsi
  XMPP_RECORDER_DOMAIN: recorder.jitsicluster.eastus.cloudapp.azure.com
  XMPP_SERVER: 10.0.43.234 # CHANGE TO WEB SERVICE CLUSTER IP
  #XMPP_DOMAIN: meet.jitsi
  XMPP_DOMAIN: jitsicluster.eastus.cloudapp.azure.com
  ENABLE_GUESTS: "1"
  #XMPP_GUEST_DOMAIN: guest.meet.jitsi
  XMPP_GUEST_DOMAIN: guest.jitsicluster.eastus.cloudapp.azure.com
  JIBRI_XMPP_USER: jibri
  JIBRI_XMPP_PASSWORD: jibriAuthPass123
  JIBRI_BREWERY_MUC: JibriBrewery
  JIBRI_RECORDER_USER: recorder
  JIBRI_RECORDER_PASSWORD: jibriRecorderPass123
  JIBRI_RECORDING_DIR: /config/recordings
  JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: /config/finalize.sh
  JIBRI_STRIP_DOMAIN_JID: muc
  JIBRI_LOGS_DIR: /config/logs
  JIBRI_PENDING_TIMEOUT: "90"
  DISPLAY: :0
  TZ: America/Los_Angeles
