apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-resolver
  #namespace: jibri
  namespace: jitsi
data:
  resolv.conf: |-
    nameserver 8.8.8.8
    nameserver 10.0.0.10
    search jitsi.svc.cluster.local svc.cluster.local cluster.local 
    options ndots:5
